import { MenuBar } from "@/components/menu_bar/MenuBar";
import TransactionsMenuBar from "@/components/TransactionsMenuBar";
import { auth } from "@/lib/auth";
import type { Metadata } from "next";
import { headers } from "next/headers";
import { getCategories } from "./categories/actions";
import "./globals.css";

export const metadata: Metadata = {
  title: "Balancee",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth.api.getSession({
    headers: await headers(),
  });

  const categories = session ? await getCategories() : [];

  return (
    <html lang="en">
      <body className="flex flex-col h-screen">
        {session && (
          <header className="sticky top-0 bg-muted h-fit px-6 py-4 w-full">
            <MenuBar />
          </header>
        )}

        <main className="flex-1 overflow-auto py-6">{children}</main>

        {session && (
          <footer className="sticky bottom-0 bg-muted h-fit px-6 py-4 w-full flex gap-4">
            <TransactionsMenuBar categories={categories} />
          </footer>
        )}
      </body>
    </html>
  );
}
